sudo: required
dist: trusty

branches:
  only:
    - 'master'

language: node_js
node_js:
  - 'node'
  - '6'

matrix:
  fast_finish: true

addons:
  chrome: stable

install:
  - npm install
  - npm link

before_script:
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
