branches:
  only:
    - master

environment:
  matrix:
    - nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yo
  - npm install
  - npm link

test_script:
  - node -v
  - npm -v
  - npm run lint
  - bash -c "test/test.sh"

build: off
